### ISSUE TITLE
SX Aurora branch merged to master

### ISSUE THREAD

**Issue by kruus** [necla-ml/gen-dnn#3]
### Description
Let's deprecate the Aurora branch that @efocht and @cdmalon have gotten working.
The [PR](https://github.com/necla-ml/gen-dnn/pull/1) into master seems to be working just fine.
Thanks!

- [x] ok for gcc (x86)
- [x] ok for ncc (Aurora)
- [x] ok for sxcc (NEC SX)

**Comment by kruus** [comment]
ve_exec support is now via CMAKE_CROSSCOMPILING and CMAKE_CROSSCOMPILING_EMULATOR

**TODO:**

- [x] Aurora as a Toolchain file (currently cmake *slowly* goes through a long list of potential compilers)
- [x] Aurora ccom SIGSEGV errors should silently retry the compile a few times
